source 'https://rubygems.org'
ruby '2.1.5'

gem 'better_errors'
gem 'bourbon'
gem 'bitters'
gem 'clearance'
gem 'coffee-rails', '~> 4.0.0'
gem 'high_voltage'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'neat'
gem 'rails', '4.1.8'
gem 'refills'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim-rails'
gem 'spring', group: :development
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
